---
blank_issues_enabled: false
contact_links:
  -
    about: "Please ask and answer usage questions in Discussions."
    name: Question
    url: "https://github.com/tony-lang/tony/discussions"
  -
    about: "Please raise issues about the compiler on its own repo."
    name: CLI
    url: "https://github.com/tony-lang/tony/issues/new"
  -
    about: "Please raise issues about the CLI on its own repo."
    name: CLI
    url: "https://github.com/tony-lang/cli/issues/new"
  -
    about: "Please raise issues about the site on its own repo."
    name: Website
    url: "https://github.com/tony-lang/tony-lang.github.io/issues/new"
